modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_containers_v0"
  version = "${file.jarVersion}"
  displayName = "Fabric Containers (v0)"
  logoFile = "assets/fabric-containers-v0/icon.png"
  authors = "FabricMC"
  description = "Adds hooks for containers."
provides = ["fabric-containers-v0"]

    [[dependencies.fabric_containers_v0]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_containers_v0]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_containers_v0]]
      modId = "fabric_api_base"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_containers_v0]]
      modId = "fabric_networking_api_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
