modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_data_generation_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Data Generation API (v1)"
  logoFile = "assets/fabric-data-generation-api-v1/icon.png"
  authors = "FabricMC"
  description = "Allows for automatic data generation."
provides = ["fabric-data-generation-api-v1"]

    [[dependencies.fabric_data_generation_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_data_generation_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"
