modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_entity_events_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Entity Events (v1)"
  logoFile = "assets/fabric-entity-events-v1/icon.png"
  authors = "FabricMC"
  description = "Events to hook into entities."
provides = ["fabric-entity-events-v1"]

    [[dependencies.fabric_entity_events_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_entity_events_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"
