modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"
displayTest = "IGNORE_ALL_VERSION"

[[mods]]
  modId = "fabric_key_binding_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Key Binding API (v1)"
  logoFile = "assets/fabric-key-binding-api-v1/icon.png"
  authors = "FabricMC"
  description = "Key Binding registry API."
provides = ["fabric-key-binding-api-v1"]

    [[dependencies.fabric_key_binding_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_key_binding_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"
