modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_transfer_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Transfer API (v1)"
  logoFile = "assets/fabric-transfer-api-v1/icon.png"
  authors = "FabricMC"
  description = "A common API for the transfer of fluids, items and other game resources."
provides = ["fabric-transfer-api-v1"]

    [[dependencies.fabric_transfer_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_transfer_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_transfer_api_v1]]
      modId = "fabric_api_lookup_api_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_transfer_api_v1]]
      modId = "fabric_rendering_fluids_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
