modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_resource_conditions_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Resource Conditions API (v1)"
  logoFile = "assets/fabric-resource-conditions-api-v1/icon.png"
  authors = "FabricMC"
  description = "Allows conditionally loading resources."
provides = ["fabric-resource-conditions-api-v1"]

    [[dependencies.fabric_resource_conditions_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_resource_conditions_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"
