modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_mining_level_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Mining Level API (v1)"
  logoFile = "assets/fabric-mining-level-api-v1/icon.png"
  authors = "FabricMC"
  description = "Adds support for custom mining levels."
provides = ["fabric-mining-level-api-v1"]

    [[dependencies.fabric_mining_level_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_mining_level_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_mining_level_api_v1]]
      modId = "fabric_api_base"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_mining_level_api_v1]]
      modId = "fabric_lifecycle_events_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_mining_level_api_v1]]
      modId = "fabric_resource_loader_v0"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
