modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"
displayTest = "IGNORE_ALL_VERSION"

[[mods]]
  modId = "fabric_renderer_indigo"
  version = "${file.jarVersion}"
  displayName = "Fabric Renderer - Indigo"
  logoFile = "assets/fabric-renderer-indigo/icon.png"
  authors = "FabricMC"
  description = "Default implementation of the Fabric Renderer API."
provides = ["fabric-renderer-indigo"]

    [[dependencies.fabric_renderer_indigo]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_renderer_indigo]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_renderer_indigo]]
      modId = "fabric_api_base"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_renderer_indigo]]
      modId = "fabric_renderer_api_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
