modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_dimensions_v1_testmod"
  version = "${file.jarVersion}"
  displayName = "Fabric Dimensions (v1) Test Mod"
provides = ["fabric-dimensions-v1-testmod"]

    [[dependencies.fabric_dimensions_v1_testmod]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_dimensions_v1_testmod]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_dimensions_v1_testmod]]
      modId = "fabric_dimensions_v1"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
