archivesBaseName = "fabric-command-api-v2"
version = getSubprojectVersion(project)

moduleDependencies(project, [
	'fabric-api-base',
])

loom {
	accessWidenerPath = file('src/main/resources/fabric-command-api-v2.accesswidener')
}

testDependencies(project, [
	':fabric-lifecycle-events-v1',
])

dependencies {
	compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
}
