modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_command_api_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Command API (v1)"
  logoFile = "assets/fabric-command-api-v1/icon.png"
  authors = "FabricMC"
  description = "Adds command-related hooks."
provides = ["fabric-command-api-v1"]

    [[dependencies.fabric_command_api_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_command_api_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_command_api_v1]]
      modId = "fabric_api_base"
      mandatory = true
      versionRange = "[0, )"
      ordering = "NONE"
      side = "BOTH"
