modLoader = "lowcodefml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
  modId = "fabric_transitive_access_wideners_v1"
  version = "${file.jarVersion}"
  displayName = "Fabric Transitive Access Wideners (v1)"
  logoFile = "assets/fabric-transitive-access-wideners-v1/icon.png"
  authors = "FabricMC"
  description = "Contains transitive access wideners that provide access to otherwise inaccessible Minecraft code."
provides = ["fabric-transitive-access-wideners-v1"]

    [[dependencies.fabric_transitive_access_wideners_v1]]
      modId = "forge"
      mandatory = true
      versionRange = "[40.3.12,)"
      ordering = "NONE"
      side = "BOTH"

    [[dependencies.fabric_transitive_access_wideners_v1]]
      modId = "minecraft"
      mandatory = true
      versionRange = "[1.18.2,1.19)"
      ordering = "NONE"
      side = "BOTH"
